export enum CounterActionsNamesEnum {
  INCREMENT = "COUTER/INCEREMNT",
  DECREMENT = "COUNTER/DECREMENT",
  POW = "COUNTER/POW",
  POW_BY_VALUE = "COUNTER/POW_BY_VALUE",
  MULTIPLY = "COUNTER/MULTIPLY",
  DIVIDE = "COUNTER/DIVIDE",
}
