export enum BasketAsyncThunkNameEnum {
  ADD = "BASKET_ASYNC/ADD_PRODUCT",
  REMOVE = "BASKET_ASYNC/REMOVE_PRODUCT",
  CHANGE_QUANTITY = "BASKET_ASYNC/CHANGE_QUANTITY",
  CLEAR_BASKET = "BASKET_ASYNC/CLEAR_BASKET",
}
