export enum BasketAsyncThunkNameEnum {
  ADD = "BASKET_ASYNC_REDUX_IN_THUNK/ADD_PRODUCT",
  REMOVE = "BASKET_ASYNC_REDUX_IN_THUNK/REMOVE_PRODUCT",
  CHANGE_QUANTITY = "BASKET_ASYNC_REDUX_IN_THUNK/CHANGE_QUANTITY",
  CLEAR_BASKET = "BASKET_ASYNC_REDUX_IN_THUNK/CLEAR_BASKET",
}
